export { default as profile } from './profile.jpg';
export { default as headerImage } from './headerImage.png';
export { default as htmlCss } from './logo/html-css.png';
export { default as jsLogo } from './logo/js.png';
export { default as bootstrapLogo } from './logo/bootstrap.png';
export { default as pythonLogo } from './logo/python.png';
export { default as typescriptLogo } from './logo/typescript.png';
export { default as vueLogo } from './logo/vue.png';
export { default as reactLogo } from './logo/react.png';
export { default as phpLogo } from './logo/php.png';
export { default as laravelLogo } from './logo/laravel.png';
export { default as sassLogo } from './logo/sass.png';
export { default as tailwindLogo } from './logo/tailwind-css.png';
export { default as mysqlLogo } from './logo/mysql.png';
export { default as jiraLogo } from './logo/jira.png';
export { default as gitHub } from './logo/github.png';
export { default as nodeJs } from './logo/nodeJs.png';

export { default as checkIcon } from './icons/check.png';